### ISSUE TITLE
Instructions not updated for installing on CC 2014 Mac

### ISSUE THREAD

**Issue by FelixLapointe** [fnordware/AdobeWebM#13]
In both library folders, both system and user, the Adobe folder in Application Support does not have the folder structure described in the Read Me. I recreated those folders but CC 2014 won't see the plugin.

**Comment by fnordware** [comment]
Works for me in OS X 10.9.5, Premiere Pro CC 2014.

/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/WebM Premiere.bundle

**Comment by ianmcgregor** [comment]
I think the confusion comes from the plug-ins folder being in the root library, not the /Users/me/Library folder.

You can open the correct folder for CC 2014 in finder by pasting this in terminal: 

```
open /Library/Application\ Support/Adobe/Common/Plug-ins/7.0/MediaCore/
```

**Comment by fnordware** [comment]
We will eventually have installers, so users won't have to know how Mac OS paths work.

**Comment by fnordware** [comment]
Installers are posted. Give them a try.
