### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by ghost** [fnordware/AdobeWebM#14]
This plugin is great. I just find out about this codec. I am having some issues:
I am exporting 45min 1920*1080 30p 50mbps using Adobe premiere pro cs6. It takes 42 min using H.264 and file size is 2134MB for YOUTUBE 1080p 29p preset. 

Webm drops the file size to 247MB estimated with default settings. It takes 3h to export and output file is 2.9GB. If I change the bit rate to 70 from 50. It takes same time and same size output. The estimated is way off from real. This is VP8. 

Is this a issue?

**Comment by fnordware** [comment]
I get the same result. This might just be a behavior of VP8 when using such a low bit rate for this resolution. If I shrink the frame way down to 256 pixels wide, then changing the bit rate from 50 to 70 kb/s does make a different file size. This is using the Variable Bitrate encoding option.

Perhaps you meant to use the Constant Quality encoding option? That's the option where 50 is the default. Using that option I would expect a bigger file, and an even bigger one if you up the quality to 70.

The red flag there is your H.264 is 2134MB while the WebM is 247 MB. The should tell you that you are using a very low bitrate. WebM (VP8) and H.264 will have about the same quality for the same file size.
