### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by G0el** [fnordware/AdobeWebM#15]
I'm not experienced with installing plugins for Adobe products - I need to be able to import .webm files into Premiere Pro CS 5.5, and my search led me to this plugin.

Where could I find detailed installation instructions?  I looked in the readme files, but couldn't figure out what to do.

Thanks :).

**Comment by fnordware** [comment]
Really, this snippet from the ReadMe isn't clear? (Not sure how many people are still using a CSX version though.)

Installation
============

Copy the plug-in to the shared MediaCore directory:

Mac:
WebM Premiere.bundle -> /Library/Application Support/Adobe/Common/Plug-ins/CSX/MediaCore

Win:
WebM.prm -> C:\Program Files\Adobe\Common\Plug-ins\CSX\MediaCore


Replace "CSX" with your version.  For the latest Premiere Pro CC release, it will be "7.0".

**Comment by fnordware** [comment]
OK, I edited the ReadMe. Now it says this:

Installation
============

Copy the plug-in to the shared MediaCore directory:

Mac:
WebM Premiere.bundle -> /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore

Win:
WebM.prm -> C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore


For older versions of Premiere, replace "7.0" with "CS6" or whatever.

**Comment by G0el** [comment]
Ahh, this is what I couldn't find.  I found two ReadMes in the files, but neither of them had this info, so I must not have found the right ReadMe, my fault, not yours, so thanks for reproducing it here :).

**Comment by fnordware** [comment]
Well, that ReadMe was included with the copy of the plug-in you downloaded.
