### ISSUE TITLE
VP8 totally bombs Premiere Pro

### ISSUE THREAD

**Issue by CaptSaltyJack** [fnordware/AdobeWebM#16]
Total crash when exporting to VP8 format.

Crash log: http://pastebin.com/izJkJgJa

**Comment by fnordware** [comment]
A new beta was posted 5 days ago, is that the one you're using?

Can you give me some more details about the settings you're using?

Thanks for the Crash log.

**Comment by nonmetalhail** [comment]
I'm having the same issue with Premiere and Media Encoder. It crashes the whole program when you try to encode WebM. I am using the most up to date beta.

**Comment by fnordware** [comment]
I'll say it again: please detail the settings you're using, version of Premiere, OS, and describe the footage you're trying to encode.

Also, does it matter if you switch between hardware accelerated rendering and software-only?

I have not been able to duplicate these crashes.

**Comment by nonmetalhail** [comment]
Happens on both OSX10.10 and 10.9
Media Encoder CC 2014 build 8.2.0.54

Both hardware and software crash.
Just trying to do a simple convert from *.mov and *.mp4 to *.webm. What other settings do you want to know?

**Comment by fnordware** [comment]
What resolution? VP8 or VP9? Constant Quality/Constant Bitrate/Variable Bitrate? What quality/bitrate are you using?

**Comment by nonmetalhail** [comment]
I had actually not noticed the VP8/VP9 radio. VP9 works. VP8 crashes. Both had the same settings.

Resolution: 1080 x 1920
Constant Quality
Quality: 50
Encoding: Good

**Comment by fnordware** [comment]
OK, I was able to get it to crash on OS X 10.9! It seems like it may just have been a problem with the file that was posted. I re-did beta 17 and re-uploaded. Can you re-download and try it out?

**Comment by nonmetalhail** [comment]
Yes! That worked. Thanks for the quick fix.
