### ISSUE TITLE
Is it possible to encode with alpha channel?

### ISSUE THREAD

**Issue by estock** [fnordware/AdobeWebM#17]
Wondering if there is an option or argument to encode with alpha channel

**Comment by fnordware** [comment]
WebM has flirted with the idea of doing alpha channels, but they haven't really committed to it. At one point they were going to add alpha to VP9, but they scrapped that idea.

You can see they have an old [wiki page](http://wiki.webmproject.org/alpha-channel) on ways to do alpha, along with some [code](https://chromium.googlesource.com/webm/webm-tools/+/master/alpha_encoder/alpha_encoder.cc) and a [demo page](http://simpl.info/videoalpha/). I'm inclined not to add alpha support when it's so unofficial, but it could be done.

You could start a thread on a [WebM discussion list](http://lists.webmproject.org/) to get a more definitive answer. [Here's](https://groups.google.com/a/webmproject.org/d/msg/webm-discuss/g9IWwG05KYA/peOGYGX8TeoJ) a relevant discussion from last year.

**Comment by ottonascarella** [comment]
Hey there,

VP9 Supports alpha channel since 2013:

https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video

**Comment by fnordware** [comment]
It's not actually in the codec, but a hack to add an additional transparency stream into the WebM file. It's only ever been supported in Chrome.

**Comment by ottonascarella** [comment]
so why VP9 has 10, 12bit options?

**Comment by fnordware** [comment]
Well, VP9 does support 10- and 12-bit, but those are for the YUV channels. It does not allow you to add a fourth channel (Alpha). VP9 can also do 4:2:2 and 4:4:4 sampling, but that is still just YUV, no alpha.

So there are three separate considerations:
1. How many channels?
2. What is the sample rate for each channel?
3. How many bits in each sample?

So for VP8/9, the answers are:
1. Always 3, YUV (aka YCbCr) (no alpha)
2. Usually 4:2:0, but VP9 can do 4:2:2 and 4:4:4
3. Usually 8, but VP9 can do 10 and 12

At one point Google was thinking of letting VP9 accept an alpha channel, but they abandoned that.

**Comment by oallouch** [comment]
So, what do you think is the simplest way to get a WebM HTML5 video for Chrome with an alpha channel from After Effects ?

Thx in advance,

Olivier

**Comment by fnordware** [comment]
I don't know of an easy way. There is some sample code [here](https://chromium.googlesource.com/webm/webm-tools/+/master/alpha_encoder/alpha_encoder.cc).

I'm just not sure it's a good idea to add support to the plug-in when only Chrome supports WebM w/ alpha.

**Comment by oallouch** [comment]
Ok, thx anyway.
I went the png/mp3-remux-using-ffmpeg path. It works well (careful not to use vp9)

**Comment by keerah** [comment]
Yes. There must be alpha support.

**Comment by fnordware** [comment]
It works in Chrome, but not Firefox. Anyone know about IE? Opera?

**Comment by geduldig** [comment]
+1 for alpha support

**Comment by while0pass** [comment]
@fnordware In Opera it works. In IE with [WebM Media Foundation Components] (https://tools.google.com/dlpage/webmmf/) it does not.

**Comment by ttoinou** [comment]
This is interesting unfortunately I doubt you can reimport back the footage into AE or Premiere Pro :/ 
A compressed video codec with alpha channel could be handy
Note to @keerah : the videos on http://simpl.info/videoalpha/ are made with VP8 not VP9

**Comment by fnordware** [comment]
OK, I have a build for you guys to try. I don't have a good way to test it, but it seems to be working, at least with VP8. I'd recommend setting the Max keyframe distance parameter to something lower like 32 because for technical reasons that will be the locked-in keyframe distance.

http://www.fnordware.com/downloads/WebM_Premiere_alphaChannel_mac.zip
http://www.fnordware.com/downloads/WebM_Premiere_alphaChannel_win.zip

**Comment by fnordware** [comment]
OK, alpha channels are now in the shipping plug-in. I hope you're happy!

**Comment by miku1958** [comment]
Hi @fnordware Importing with alpha channels is broken. I test it with PR 2022, it can export vp9 with aplha, and the video works in OBS, but not in PR. The property of the video in PR shows that the video has no alpha channel.
