### ISSUE TITLE
Media Encoder not seeing WebM

### ISSUE THREAD

**Issue by silent1der** [fnordware/AdobeWebM#19]
I've installed the plug-in and it works great in Adobe Premiere CS6, but WebM does not appear as a supported format in Adobe Media Encoder. If I select WebM in Premiere and try to queue up the export in AME, it defaults to AAC encoding (I'm guessing because it's first, alphabetically). I have to encode straight from Premiere, so I can't batch process.

I've copied the WebM.prm file to the indicated MediaCore directory listed in the ReadMe file, including both C:\Program Files... and C:\Program File (x86)...

I'm running Windows 8.1 with Adobe Master Collection CS6 on a 64-bit Surface Pro 3. I also just ran the Adobe Updater to get the latest updates to the programs. Is there something else I should try?

**Comment by fnordware** [comment]
Works for me in Media Encoder CS6.

C:\Program Files\Adobe\Common\Plug-ins\CS6\MediaCore\WebM.prm

Remember, the ReadMe says you need to replace "7.0" with "CS6" to get the path above.

**Comment by fnordware** [comment]
Silly question, but…did you restart Media Encoder?

**Comment by silent1der** [comment]
Yes, the paths have "CS6". The directories were already there from the install of CS6. And I've restarted the programs and my computer. I've even tried:

C:\Program Files\Adobe\Adobe Media Encoder CS6\Plug-ins\Common\WebM.prm

without any luck. Thanks for responding. I really love the plug-in. Guess I'll have to keep exporting one by one in Premiere for the time being.

**Comment by fnordware** [comment]
Really weird. I guess you could send the bug to Adobe, I think CS6 is still supported. Or maybe upgrade...

**Comment by fnordware** [comment]
There's now an installer for the plug-in. Maybe you'll have better luck with that?

**Comment by adamlaughlin** [comment]
I've run the installer, and nothing shows up for WebM in Premiere or Media Encoder.
I've restarted the program, the computer, and tried "repair" after running the installer, repeating the step of restarting the computer.
The only file in the C:/Program Files/fnord software/WebM for Premiere folder is a PDF manual.

Can you make the .zip folder with the prm file available again?  I'd rather try that instead.

**Comment by fnordware** [comment]
I should probably change the Windows installer to just install the plug-in for any MediaCore folders it finds. Seems no matter which delivery method I use, there will be issues.

Since you asked, the plug-in was a decent amount of work to get something working, and then I made various smaller changes from time to time. The biggest hurdle was learning how to write movie files from Premiere, and then learning how to use libvpx, libvorbis, and libopus. Now that I've learned all that stuff, the plug-in doesn't seem too complicated anymore.

**Comment by AiacPL** [comment]
I got the same issue. I put plugin file into every folder I found which may be related to plugins, even into Program Files (x86)/Adobe (...).

Somebody wrote a post on adobe's forums that he cant see QT in export list. It was related to the file:
C:\Program Files\Adobe\Adobe Media Encoder CS6\txt

Maybe adding some lines there will fix the problem?

When im exporting project into media from Premiere and choose WebM, then "queue in media encoder" it changes itself in ME into "AAC audio"...

**Comment by arosearose** [comment]
I can see webm as export option in CS6 Premier but I don't see it as a supported format in CS6 Media Encoder .  haven't figured out why yet...

**Comment by arosearose** [comment]
Windows 10, CS6 Premier, Export> Media> choose webm, export status bar stays at 0%  "forever"
ugh

**Comment by fnordware** [comment]
Another thing you could try: hold down shift while the program loads. This clears prefs in Premiere, maybe Media Encoder too?

Or I don't know if you can still access Adobe Add-ons (previously called Adobe Exchange) from CS6, but it's [here](https://creative.adobe.com/addons/products/11631).

**Comment by arosearose** [comment]
How very great of you to email me. I'll try these things.  I waited a while trying to export 90 second clip from premier.  Premier is saying the export will take 52 hours. Lol. Is that to be expected? 


Thanks for the plug in and your time. Very generous. 

Sent from Yahoo Mail on Android

**Comment by fnordware** [comment]
52 hours for a 90 second clip? Yikes. What are your settings? What is the resolution?

**Comment by arosearose** [comment]
running windows 10, CS6, premier,  export>media, set format to webm 

no dialog box was invoked to ask for settings, maybe I'm supposed to see setting change when I select the webm format.
I'll get the facts you've requested when I return home, where the machine is.
thanks-a
 Andrew Rose LPC, MA, Director, Boulder Emotional Wellness  
Play Therapy, Couples, Individual EMDR & Brainspotting, Individual Wilderness Trips  Step Into Counseling

**Comment by MrHOTnSPICY** [comment]
I am hoping to revive this matter since I am having exactly the same issue:

Can export to WebM via Premiere Pro CS6, but can not even choose WebM inside Media Encoder CS6 (which I use more often).

The system is Windows 10 and I have the plugin in both, C:\Program Files\Adobe\Common\Plug-ins\7.0 \MediaCore\WebM.prm and C:\Program Files\Adobe\Common\Plug-ins\CS6\MediaCore\WebM.prm

It would be very much appreciated, if I can get assistance sorting this out. Cheers.

**Comment by fnordware** [comment]
Seems to me like you should have everything in the right place. For fun (?) you could try putting a copy of the plug-in in the application-specific plug-in folder for Media Encoder.

What happens when you select WebM in Premiere and then click the Queue button to send the job to Media Encoder?

I assume you've tried restarting.

**Comment by timschuermann** [comment]
I've had the same problem in CS6 and Windows 10: WebM didn't appeared in the Media Encoder.

In my case the solution was simple: In CS6 there are two Media Encoders: one 64 bit version and one 32 bit version. After the installation of the whole CS6 suite the start menu of Windows 10 lists only the 32 bit version of the Media Encoder. But the WebM plugin is only available in the 64 bit version of the Media Encoder. So if I start the Windows Explorer, navigate to the directory

C:\Program Files\Adobe\Adobe Media Encoder CS6\

and double click on the executable of the 64 bit version of the Media Encoder, the WebM formats are available.

**Comment by MrHOTnSPICY** [comment]
Thank you Tim!! Checked and just as you said. Working fine, it was just me overlooking something obvious. Man, I feel stupid now...

**Comment by fnordware** [comment]
Ahhh, good one, Tim.

I guess this didn't come up in Premiere because it's only 64-bit.
