### ISSUE TITLE
Taking hours to encode a 2 min MOV

### ISSUE THREAD

**Issue by ottonascarella** [fnordware/AdobeWebM#21]
Hi there,

First off, thanks for writing this.
We all want to be able to use webm, and this plugin is certainly a good help.

I was trying to use the plugin but it is taking ages to convert a file.
I just used the plugin on its default state.

any tips?

**Comment by kadri55** [comment]
![11393232_1010438765633211_6826684583047295390_n](https://cloud.githubusercontent.com/assets/8591636/9343951/e2b43792-460d-11e5-98f5-e5a10c9b8fe6.jpg)

**Comment by fnordware** [comment]
VP9 is a high-quality codec, but pretty slow. You'll get a big speed-up (but lose quality) if you use VP8 instead.

Another thing you can try is using the custom args field, and putting "--cpu-used=3" or numbers higher than 3. This should turn off some VP9 features and speed things up (again, losing some quality).

More info on custom arguments [here](http://www.webmproject.org/docs/encoder-parameters/). Or you can post on the [WebM discussion forum](http://groups.google.com/a/webmproject.org/group/webm-discuss/).
