### ISSUE TITLE
WebM Plugin not on site for Mac

### ISSUE THREAD

**Issue by ruhlandt** [fnordware/AdobeWebM#22]
Where is the plugin for Mac? It is not showing up on the page...

**Comment by fnordware** [comment]
Hopefully it's back now, right? My web hosting company had an outage.

http://www.fnordware.com/WebM/

**Comment by ruhlandt** [comment]
Nope, still not there. For download all it shows is the pluggin for Photoshop, but not for Premiere. Hmmm, am I just not lookin in the right place?

**Comment by fnordware** [comment]
The Photoshop links are found in the front page of this repo:

https://github.com/fnordware/AdobeWebM

Premiere links are on the fnordware.com website:

http://www.fnordware.com/WebM/

This is because the Premiere plug-in is considered released but the Photoshop one is not.

**Comment by ruhlandt** [comment]
Ohhhhh, okay. Thank you so much. I got it! :D
