### ISSUE TITLE
[WEBP] memory return problem and...

### ISSUE THREAD

**Issue by m88r** [fnordware/AdobeWebM#28]
![webp](https://cloud.githubusercontent.com/assets/16315627/11832116/6b250ec4-a3f8-11e5-9d21-c07a6a15e8ea.jpg)
photoshop cs6 64bit

after saving the 40 images as webp and jpg

and
can't save as Grayscale

**Comment by fnordware** [comment]
Yep, that's a memory leak! Hopefully I've now plugged it. Download the new beta and let me know how it goes.

Thanks for the bug report!

**Comment by m88r** [comment]
110MB~130MB  stable
Thanks!

**Comment by fnordware** [comment]
BTW, WebP doesn't support grayscale, so that's why I don't have that option in Photoshop.
