### ISSUE TITLE
Super slow encoding times in Premiere Pro CC

### ISSUE THREAD

**Issue by DJviolin** [fnordware/AdobeWebM#3]
Hi! I have a 720p, 5minute, 25fps footage, which I need to convert in webm, because Chrome seems like doesn't support h.264. First I will convert with constant bitrate (final file around 150mb), later with Constant Quality (what is this exactly? It will hold the same quality but in less file size?)

Media Encoder CC says encoding time is 26hours! (same in PP). Is it normal for VP9 codec, or better if I try to find other software to finish it earlier?

**Comment by rlschroeder** [comment]
One interesting thing I noticed that on a quad-core i7 machine I have, all the cores are used at nearly full speed when encoding with the latest webM beta. On a six-core nMP, though, the CPU usage barely jumps. Encoding time estimate on both machines are similar, though. Odd?

**Comment by fnordware** [comment]
rlschroeder, are you doing VP8 or VP9? VP9 tends to not use a lot of CPU because it's not multithreaded yet. It'll occupy most of one CPU. So if you're doing VP9, the CPU use on the other machine more reflects what Premiere is doing, not WebM.

**Comment by rlschroeder** [comment]
I'm using VP8 for that encode.

**Comment by rlschroeder** [comment]
Here's my preset settings and Activity Monitor comparisons between the two machines.

![screen shot 2015-01-13 at 1 36 44 pm](https://cloud.githubusercontent.com/assets/9218328/5729773/c9f1e4be-9b29-11e4-8116-f18136e0fb5e.png)

![screen shot 2015-01-13 at 1 35 24 pm](https://cloud.githubusercontent.com/assets/9218328/5729775/cf41df3c-9b29-11e4-8bbf-b6371c0ba97a.png)

![screen shot 2015-01-13 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/9218328/5729776/d1fa7310-9b29-11e4-928c-9220ba555cad.png)

**Comment by fnordware** [comment]
Interesting. Any idea about how many frames per second the encoding is working at?

If using VP8, you should be running on multiple CPUs. You can put "--threads=2" in the custom args if you want to test with a different number of threads (2 in that case).

If the encoding takes the same time on both machines, my guess is that most of the processing is Media Encoder generating the frames and the encoding is just a blip afterward. Maybe on the computer with less CPU usage, AME is able to use the GPU?

**Comment by rlschroeder** [comment]
I'd guesstimate 8-12fps on the encode?

It's possible that the encode is just a blip. I'm not too concerned about
it; it's just an odd thing I noticed :)


RYAN SCHROEDER

**Comment by fnordware** [comment]
Try the latest build. It uses --cpu-used=2 by default and now has some multithreading. VP9 is still slower than VP8, but the gap has narrowed significantly.
