### ISSUE TITLE
Mac: No loaders recognized this plugin, so the plugin is set to Ignore.

### ISSUE THREAD

**Issue by kirkkhua** [fnordware/AdobeWebM#34]
Here is what "Plugin Loading.log" saying:

Loading /Users/kirk/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/WebP.plugin
The modification date has changed so the plugin will be loaded from disk.
Loading from disk...
No loaders recognized this plugin, so the plugin is set to Ignore.

Thus, plugin is not loaded and not working on Premiere Pro CC.

**Comment by fnordware** [comment]
WebP is a Photoshop plug-in, not a Premiere plug-in. It won't work in Premiere.
