### ISSUE TITLE
No WebM.prm

### ISSUE THREAD

**Issue by Bradum** [fnordware/AdobeWebM#43]
Hi,

I downloaded the installer, but it doesn't seem to want to install the WebM.prm file. It only installs the 'presets' forlder, and the PDF manual.

Tried to get it to install on my laptop as well, but same issue.

![image](https://user-images.githubusercontent.com/31322679/29684314-80068e62-88df-11e7-8984-28c544eae30a.png)

**Comment by fnordware** [comment]
The plug-in should be in C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore

**Comment by Bradum** [comment]
Derp. I had installed a friend's Creative Cloud version to see if I wanted to upgrade. So I thought that's where the 7.0 came from.

**Comment by Bradum** [comment]
So now the WebM.prm file is showing up as well, but premiere pro is not recognizing it as an exportable format. I've tried restarting both Premiere Pro, as well as my computer.

![image](https://user-images.githubusercontent.com/31322679/29698361-e72e50e6-8922-11e7-9fcd-990e57afdd92.png)


![image](https://user-images.githubusercontent.com/31322679/29698351-d9db9e62-8922-11e7-9c1b-c878d8da821d.png)

**Comment by jpcartailler** [comment]
I have the same issue as @Bradum. Running Premiere Pro CS6 (6.0.5) in Win10. I can't import/export WebM. The plugin appears to be in the right location:

![image](https://user-images.githubusercontent.com/5258731/30128806-9879d90c-9309-11e7-82c5-f1b4bc8075fe.png)

Tried media encoder too, with the same results.

**Comment by fnordware** [comment]
If you're using CS6, you'll have to copy the plug-in from
C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore
to
C:\Program Files\Adobe\Common\Plug-ins\CS6\MediaCore

**Comment by jpcartailler** [comment]
Thank you @fnordware! I'm in business now!

**Comment by Bradum** [comment]
Worked for me as well. Thanks!
