### ISSUE TITLE
Media Encoder CC 2014 Crash on Export

### ISSUE THREAD

**Issue by MiniHobbit** [fnordware/AdobeWebM#7]
While exporting through Encoder CC works perfectly, exporting through the new Encoder CC 2014 results in the following crash. Thought I'd give you the heads up:

Using either VP8 or VP9 codec on 24, 25 or 30 fps at multiple 4k resolutions (3840x2160 / 4096x2304) results in a failed export. 

The source is an MP4 1080p file. I'm trying to upscale. Used both Opus and Vorbis audio settings. Duration of the clip is 10 seconds.

![error](https://cloud.githubusercontent.com/assets/8182228/3601897/bb13a516-0d05-11e4-87b8-9c351b961c95.png)

Again, no troubles in the old encoder. Just in CC 2014.

**Comment by neil-119** [comment]
For me, it didn't crash, but it gave me an absolutely *hilarious* goat noise. I'm not kidding. I was like WTF and I tried it again. Goat noise.

The error logs said:

	-------------------------------------------------------
	 - Encoding Time: 00:00:11
	03/10/2015 10:03:18 PM : Encoding Failed
	-------------------------------------------------------
	Export Error
	Error compiling movie.

	 Unknown error.
	-------------------------------------------------------

I was going FROM webm TO H.264 mp4, if it helps.

**Comment by fnordware** [comment]
Yeah, that sheep noise goes waaaay back to early versions of After Effects. It's the sound of a failed render, as opposed to the brrrrrrring sound you got on success.

Anyway, I have to ask the usual questions:

Which version of Premiere/AME? Which OS? Latest WebM plug-in? What were your WebM settings? What is your footage size/codec/etc? Can I maybe get said footage? Are you doing hardware or software rendering?

**Comment by neil-119** [comment]
It's like an "Easter egg" in their software, if it could be classified as
such. It was hilarious. Anyway...

Adobe Media Encoder v2014 build 8.0.0.173
Windows 8.1
Latest WebM plug-in
No screen opened up for webm settings. I tried going from webm to mov, mp4,
etc.
Footage was a screen recording of a chrome tab (screencast).
You sure can, except I don't want to post the footage publicly. Where
should I send it to?
I'm not sure if it was hardware or software. They were the default settings.

**Comment by fnordware** [comment]
If it's small enough, you can [e-mail](mailto:info@fnordware.com) me a file, or a link. I don't have a place for you to upload to.

**Comment by santacruzskim** [comment]
having the same problem. Installed on a 2010 mac pro, 2012 mac pro, and 2013 mac pro and only the 2012 doesn't error out. all have same plugin and adobe software versions. i've tried CPU vs GPU, pretty much every encoder parameter combination on the planet... not sure what the deal is :(

**Comment by fnordware** [comment]
OK, I was finally able to reproduce! Try the new beta and let me know if you still have problems.

The key is that someone finally sent me their footage. Here is what my informative bug report would have looked like:

Media Encoder CC 2014 (2014.2 release, build 8.2.0.54)
OS X 10.9.5
MXF from Sony camera: 1920x1080, 25 fps, Upper field, 8 channel audio
WebM settings: default (VP8, Quality 50)

Steps:
1. Import footage into Media Encoder
2. Pick WebM format from dropdown at left
3. Hit play button to begin encoding

Get an exception error immediately.


(Turns out the problem was the 8 channel audio.)

**Comment by fnordware** [comment]
Think we've got the various format issues covered now. Open a new issue if you find a problem. Include settings, input video format details, and if possible…footage!
