### ISSUE TITLE
Can't export any media in Premiere 22.2

### ISSUE THREAD

**Issue by derekashauer** [fnordware/AdobeWebM#79]
Once installed, I have lost **all** ability to export anything from Adobe Premiere.  File > Export > Media does absolutely nothing after installing this. How do you uninstall so I can use Premiere again?

**Comment by adamfehnel** [comment]
I had the same issue, I'm on an M1 Mac.  Tried a few things but what worked for me was reinstalling Media Encoder with the /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/WebM Premiere.bundle file TRASHED, confirmed it worked by opening an After Effects Composition, then closing Media Encoder, restore the .bundle file from my trash to that path, then booting up Media Encoder again.  Hope that helps someone else in the future.
