### ISSUE TITLE
Latest beta doesn't seem to work in latest Adobe release (2014.1)

### ISSUE THREAD

**Issue by rlschroeder** [fnordware/AdobeWebM#9]
Renders fail in latest Adobe release (2014.1). 

AME simply gives the following error:

-------------------------------------------------------
 - Encoding Time: 00:00:00
10/14/2014 10:08:47 AM : Encoding Failed
-------------------------------------------------------
Export Error

Error compiling movie.

 Unknown error.

**Comment by zotsf** [comment]
I encountered the same error with the WebM plugin trying to export a video file, but solved it.

I'm running OSX 10.9.5 and Adobe CC 2014.2

I unchecked the Export Audio box and it worked.

**Comment by fnordware** [comment]
Well, obviously that is not cool if you can't export audio. If I could replicate this problem, I could fix it.

First step is to tell me which version of Premiere on which operating system and every setting you're using so I can try the same settings.

If I don't get the same bug with the same settings, then I might need some footage because Premiere will do different things when exporting different types of footage.

**Comment by zotsf** [comment]
Thanks for checking! I'm sorry to take so long to get back to you :/  I'm
just now coming back to this project.

I'm running
OSX 10.9.5
Premiere Pro in creative cloud 2014.2 v8.1

Video settings:
webm
export video and audio
image settings: match source
pixel aspect ratio: D1/DV NTSC (0.9091)
Codec Settings: VP8, constant quality, quality at 50, encoding good,
sampling 4:2:0

Audio:
sample rate: 44100hz
channels: mono
Codec: vorbis
Method: quality
Quality: 0,5

**Comment by fnordware** [comment]
So I exported a DV file (720x480) with the same settings and configuration and it worked fine. Probably need to get some footage from you to have any hope of duplicating.

**Comment by fnordware** [comment]
I just posted a new beta that fixes a similar problem. Try it and let me know if you still have problems.

And if you do, send me some footage!

**Comment by fnordware** [comment]
Think we've got this bug fixed.
